- hosts: k8s_node
  gather_facts: false
  any_errors_fatal: true
  vars:
    vars_path_arg: "--vars-path {{ ki_tmp_vars_path }}"
  tasks:
    - when: inventory_hostname == k8s_cp_nodes | first
      block:
        - name: "Drain node[\"{{ upgrade_node }}\"]"
          shell: "sudo {{ ki_env_scripts_path }}/k8s-node/k8s-upgrade/drain-node.sh {{ vars_path_arg }}"
